<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="css/ShopStyle.css" />
</head>
<body>
<div id="header">
	<div class="shell">  
		
	
		<div id="navigation">
			<ul>
			    <li><a href="ShopIndex.php" title="Shop"><span>Shop</span></a></li>
			    <li><a href="VoucherBalance.php" title="Voucher Balance"><span>Voucher Balance</span></a></li>
			    <li><a href="SpentVouchers.php" title="Spent-Vouchers list"><span>Spent-Vouchers list</span></a></li>
			    <li><a href="/aps-webpages/aps/index.php" title="Change Destination"><span>Change Destination</span></a></li>
			</ul>
		</div>

	</div>
</div>

	<div id="featured-content">
		<div class="shell">
			<h2>welcome</h2>
			<p>to the shop</p>
		</div>
	</div>

<div id="main">
	<div class="shell">
