<div id="header">
    <div class="shell">
        <div id="navigation">
            <ul>
                <li><a href="index.php" title="Shop">Shop</a></li>
                <li><a href="voucher_wallet.php" title="Voucher Wallet">Voucher Wallet</a></li>
                <li><a href="spent_vouchers.php" title="Spent Vouchers">Spent Vouchers</a></li>
                <li><a href="../index.php" title="Change Destination">Change Destination</a></li>
            </ul>
        </div>
    </div>
</div>

<div id="featured-content">
    <div class="shell">
        <h2>welcome</h2>
        <p>to the shop</p>
    </div>
</div>
