<div id="top">
    <div id="header">
        <h1>Public Bank</h1>
    </div>

    <div id="topmenu">
        <ul>
            <li><a href="index.php" title="Bank Home">Home</a></li>
            <li><a href="voucher.php" title="Purchase Vouchers">Purchase Vouchers</a></li>
            <li><a href="account.php" title="Account">Account</a></li>
            <li><a href="login.php" title="Login">Login</a></li>
            <li><a href="../index.php" title="Change Destination">Change Destination</a></li>
        </ul>
    </div>

    <div class="clear"></div>
</div>
