<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="publicbank.css" />
</head>
<body>
<div id="section">
<div id="banner">
<div id="globalnav">
<ul>
<li><a href="bankindex.php">Home</a></li> 
<li><a href="voucher.php">Vouchers</a></li>
<li><a href="login.php">Login</a></li>
<li style="float:right"><a href="/aps/index.php">Change Destination</a></li> 
</ul>
</div>
<h2>Public Bank</h2>
</div>
</div>

<!-- end of header.inc -->
