<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="publicbank.css" />
</head>
<body>
<div id="section">
<div id="banner">
<div id="globalnav">
<a href="bankindex.php">Home</a>  
<a href="voucher.php">Vouchers </a>
<a href="account.php">Account</a>
<a href="login.php">Login</a>
<a href="/aps/index.php">Change Destination</a> 
</div>

<h2>Public Bank</h2>
</div>
</div>

<!-- end of header.inc -->
